<HTML>
<HEAD>
<meta charset="UTF-8">
<title>Wendy.resolveError - wendy</title>
<link rel="stylesheet" href="../../../style.css">
</HEAD>
<BODY>
<a href="../../index.html">wendy</a>&nbsp;/&nbsp;<a href="../index.html">com.levibostian.wendy.service</a>&nbsp;/&nbsp;<a href="index.html">Wendy</a>&nbsp;/&nbsp;<a href="./resolve-error.html">resolveError</a><br/>
<br/>
<h1>resolveError</h1>
<a name="com.levibostian.wendy.service.Wendy$resolveError(kotlin.Long)"></a>
<code><span class="keyword">fun </span><span class="identifier">resolveError</span><span class="symbol">(</span><span class="identifier" id="com.levibostian.wendy.service.Wendy$resolveError(kotlin.Long)/taskId">taskId</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-long/index.html"><span class="identifier">Long</span></a><span class="symbol">)</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-boolean/index.html"><span class="identifier">Boolean</span></a></code>
<p>Mark a previously recorded error for a <a href="../-pending-task/index.html">PendingTask</a> as resolved.</p>
<p><em>Note:</em> If your <a href="../-pending-task/index.html">PendingTask</a> belongs to a group, this function will iterate all of the <a href="../-pending-task/index.html">PendingTask</a>s of that group and resolve the first (and only the first one) error that it comes upon. This is because (1) groups allow having "duplicate" <a href="../-pending-task/index.html">PendingTask</a>s in them (2) it is assumed that if an error is resolved for one <a href="../-pending-task/index.html">PendingTask</a> in a group, the error is resolved for <em>all</em> <a href="../-pending-task/index.html">PendingTask</a>s in the group and, well, a group cannot execute if the <em>very first</em> <a href="../-pending-task/index.html">PendingTask</a> is blocking the group from executing. So with this feature, you technically only have to keep track of <em>1</em> <a href="../-pending-task/task-id.html">PendingTask.taskId</a> in your app when you call <a href="add-task.html">Wendy.addTask</a> for a <a href="../-pending-task/index.html">PendingTask</a> that belongs to a group instead of having to keep track of multiple <a href="../-pending-task/task-id.html">PendingTask.taskId</a>s for every time you call <a href="add-task.html">Wendy.addTask</a>.</p>
<p><em>Note:</em> If you attempt to resolve an error when an error does not exist in Wendy (because it has already been resolved or was never recorded) then the <a href="../../com.levibostian.wendy.listeners/-task-runner-listener/error-resolved.html">TaskRunnerListener.errorResolved</a> and <a href="../../com.levibostian.wendy.listeners/-pending-task-status-listener/error-resolved.html">PendingTaskStatusListener.errorResolved</a> will not be called.</p>
<p><em>Note:</em> If <a href="../../com.levibostian.wendy/-wendy-config/automatically-run-tasks.html">WendyConfig.automaticallyRunTasks</a> is true, the task runner will attempt to run your task after it has been resolved immediately. If the task belongs to a group, the task runner will attempt to run all the tasks in the group.</p>
<h3>Parameters</h3>
<p><a name="taskId"></a>
<code>taskId</code> - The taskId of a <a href="../-pending-task/index.html">PendingTask</a> previously recorded an error for.</p>
<h3>Exceptions</h3>
<p><a name="IllegalArgumentException"></a>
<code>IllegalArgumentException</code> - If the <a href="../-pending-task/index.html">PendingTask</a> for the taskId provided does not exist.</p>
<p><strong>Return</strong><br/>
If <a href="../-pending-task/index.html">PendingTask</a> had a previously recorded error and it has been marked as resolved now.</p>
<p><strong>See Also</strong><br/>
<p><a href="record-error.html">recordError</a></p>
</p>
</BODY>
</HTML>
